### ISSUE TITLE
Атомарное преобразование сетки. Стягивание по ребру.

### ISSUE THREAD

**Issue by r-aax** [r-aax/crys-gsu#16]
Нужно реализовать **стягивание сетки по ребру**.

_Иллюстрация:_
![collapse_edge](https://user-images.githubusercontent.com/32441244/151334525-4d539da7-cb4a-4443-8691-49c4329e7040.png)

_Функционал:_
- удаляется ребро DF.
- узлы D и F стягиваются в единый узел X.
- ребра CD и CF стягиваются в ребро CX.
- ребра ED и EF стягиваются в ребро EX.
- грани CDF и EDF удаляются.

_Интерфейс:_
```
class Grid:
    ...
    def collapse_edge(edge)
    ....
```

**Comment by freysa** [comment]
@r-aax а как тут быть с глобальным номером объектов? этот метод удалит два фейса, два ребра и точку, ничего не добавит - в центре глобальной нумерации будет дырка

**Comment by r-aax** [comment]
Надо сдвигать, глобальные идентификаторы должны быть сплошные.
Если нет иного выхода, то прямо вот так:

```
for i, f in enumerate(Faces):
    f.GloId = i
```

затратно конечно, но может потом как-то уйдем от этого

**Comment by r-aax** [comment]
хотя если жалко времени (а его жалко). можешь объекту из хвоста дать GloId из дырки
