### ISSUE TITLE
Атомарное преобразование сетки. Разбиение ребра.

### ISSUE THREAD

**Issue by r-aax** [r-aax/crys-gsu#17]
Нужно реализовать **разбиение ребра сетки** по произвольной точке.

_Иллюстрация:_
![cut_edge](https://user-images.githubusercontent.com/32441244/151337164-47c1b9e4-dd8d-4076-8074-74e6647c4980.png)

_Функционал:_
- на базе данной точки P создается новый узел X.
- вместо ребра BD создаются ребра BX и XD.
- вместо грани ABD создаются грани ABX и AXD, которые наследуют данные грани ABD.
- вместо грани CBD создаются грани CBX и CXD, которые наследуют данные грани CBD.

_Интерфейс:_
```
class Grid:
    ...
    def cut_edge(edge, p : Vector)
    ...
```

**Comment by freysa** [comment]
@r-aax обязательно перестраивать по заданному ребру или можно внутри метода определять ближайшее к точке ребро и по нему перестраивать?
