### ISSUE TITLE
Атомарное преобразование сетки. Разделение грани по точке.

### ISSUE THREAD

**Issue by r-aax** [r-aax/crys-gsu#18]
Нужно реализовать **разделение грани** по произвольной точке.

_Иллюстрация:_
![divide_face](https://user-images.githubusercontent.com/32441244/151338845-0e6381b7-baa2-4c61-9065-7279eac1c953.png)

_Функционал:_
- на базе точки P создается новый узел X.
- создаются новые ребра AX, BX, CX.
- вместо грани ABC создаются грани ABX, BCX, ACX, которые наследуют данные грани ABC.

_Интерфейс:_
```
class Grid:
    ....
    def divide_face(face, p : Vector)
    ....
```

**Comment by freysa** [comment]
@r-aax готово
