### ISSUE TITLE
Атомарное преобразование сетки. Стягивание сетки по грани.

### ISSUE THREAD

**Issue by r-aax** [r-aax/crys-gsu#19]
Нужно реализовать **стягивание сетки по грани**.

_Иллюстрация:_
![collapse_face](https://user-images.githubusercontent.com/32441244/151340845-1ac5cb03-fe15-41e7-90a2-a20b3d281dd5.png)

_Функционал:_
- по данному треугольнику ABC выбирается максимальное ребро, в сторону которого стягивается сетка (AC).
- ребро AC удаляется.
- грань ABC удаляется.
- создается ребро BD и грани ABD, CBD, которые наследуют данные грани ACD.

_Интерфейс:_
```
class Grid:
    ...
    def collapse_face(face)
    ...

```

**Comment by freysa** [comment]
@r-aax готово
