### ISSUE TITLE
Move unit tests from corresponding modules to module tests

### ISSUE THREAD

**Issue by NordMike** [r-aax/crys-gsu#25]
List of modules to change:
- [x] geom/triangle.py
- [x] gsu_geom.py

**Comment by freysa** [comment]
Ошибки, которые могут возникнуть:

Данные тесты, особенно в коммите [2c8daa0](https://github.com/r-aax/crys-gsu/commit/2c8daa0173547d82e830a417218a781f13b047c8) требуют импорта соседних скриптов, таких как gsu, box, trajectory, node, face. 
В этих соседних скриптах есть импорты utils, geom. .., gsu. ... Импорт этих библиотек вызывал исключение типа - "No module named 'geom'". Чтобы это исправить ко всем вышеупомянутым импортам ( utils, geom. .., gsu. ...) в файлах (gsu, box, trajectory, node, face) я добавлял префиксы "src." и исключение больше не вызывалось.
По просьбе Сергея, эти префиксы не были включены в коммиты.
Если подобные ошибки возникнут, то просто перед соответствующими импортами напишите "src.", как тут:

- gsu.py
import random
import math
import src.utils
from src.geom.vect import Vect
from src.geom.segment import Segment
from src.geom.triangle import Triangle
from src.geom.trajectory import Trajectory
from src.geom.box import Box
from src.gsu.node import Node
from src.gsu.edge import Edge
from src.gsu.face import Face
from src.gsu.zone import Zone
from src.gsu.zones_adjacency_matrix import ZonesAdjacencyMatrix

- trajectory.py
import math
from src.geom.vect import Vect

- box.py
import math
from src.geom.vect import Vect
from src.geom.triangle import Triangle

- node
from src.geom.vect import Vect

- face.py
import random
from src.geom.vect import Vect
from src.geom.triangle import Triangle
